<?php

namespace Database\Seeders;

use App\Models\Addon;
use Illuminate\Database\Seeder;

class AddonSeeder extends Seeder
{
    public function run(): void
    {
        $addons = [
            [
                'name'          => ['ar' => 'واتساب بزنس', 'en' => 'WhatsApp Business'],
                'slug'          => 'whatsapp',
                'description'   => ['ar' => 'أرسل تذكيرات الجلسات وإشعارات الفواتير وتحديثات القضايا لعملائك مباشرةً عبر واتساب.', 'en' => 'Send hearing reminders, invoice notifications, and case updates to your clients via WhatsApp.'],
                'icon'          => 'heroicon-o-chat-bubble-left-ellipsis',
                'price_monthly' => 99,
                'price_yearly'  => 990,
                'currency'      => 'EGP',
                'category'      => 'communication',
                'sort_order'    => 1,
            ],
            [
                'name'          => ['ar' => 'التوقيع الإلكتروني', 'en' => 'E-Signature'],
                'slug'          => 'esignature',
                'description'   => ['ar' => 'أرسل العقود والوثائق للعملاء للتوقيع إلكترونياً من هاتفهم بدون طباعة.', 'en' => 'Send contracts and documents for electronic signature directly from their phone.'],
                'icon'          => 'heroicon-o-pencil-square',
                'price_monthly' => 79,
                'price_yearly'  => 790,
                'currency'      => 'EGP',
                'category'      => 'legal',
                'sort_order'    => 2,
            ],
            [
                'name'          => ['ar' => 'المساعد القانوني AI', 'en' => 'AI Legal Assistant'],
                'slug'          => 'advanced-ai',
                'description'   => ['ar' => 'تحليل العقود وتلخيص الوثائق وصياغة المذكرات القانونية بالذكاء الاصطناعي.', 'en' => 'Analyze contracts, summarize documents, and draft legal briefs using AI.'],
                'icon'          => 'heroicon-o-sparkles',
                'price_monthly' => 149,
                'price_yearly'  => 1490,
                'currency'      => 'EGP',
                'category'      => 'ai',
                'sort_order'    => 3,
            ],
            [
                'name'          => ['ar' => 'تطبيق موبايل للعميل', 'en' => 'Client Mobile App'],
                'slug'          => 'client-pwa',
                'description'   => ['ar' => 'يتيح لعملائك تتبع قضاياهم ومواعيد جلساتهم ودفع فواتيرهم من تطبيق موبايل مخصص.', 'en' => 'Let your clients track cases, hearings, and pay invoices from a dedicated mobile app.'],
                'icon'          => 'heroicon-o-device-phone-mobile',
                'price_monthly' => 59,
                'price_yearly'  => 590,
                'currency'      => 'EGP',
                'category'      => 'client',
                'sort_order'    => 4,
            ],
            [
                'name'          => ['ar' => 'SMS تذكيرات', 'en' => 'SMS Reminders'],
                'slug'          => 'sms',
                'description'   => ['ar' => 'أرسل تذكيرات الجلسات وإشعارات المواعيد للعملاء برسائل SMS تلقائية.', 'en' => 'Send automatic SMS reminders for hearings and appointments to your clients.'],
                'icon'          => 'heroicon-o-device-phone-mobile',
                'price_monthly' => 49,
                'price_yearly'  => 490,
                'currency'      => 'EGP',
                'category'      => 'communication',
                'sort_order'    => 5,
            ],
            [
                'name'          => ['ar' => 'تقارير وتحليلات متقدمة', 'en' => 'Advanced Reports & Analytics'],
                'slug'          => 'advanced-reports',
                'description'   => ['ar' => 'تقارير مالية تفصيلية وتحليلات أداء المكتب ومعدلات نجاح القضايا وتوقعات الإيرادات.', 'en' => 'Detailed financial reports, office performance analytics, case win rates, and revenue forecasting.'],
                'icon'          => 'heroicon-o-chart-bar',
                'price_monthly' => 89,
                'price_yearly'  => 890,
                'currency'      => 'EGP',
                'category'      => 'analytics',
                'sort_order'    => 6,
            ],
            [
                'name'          => ['ar' => 'القوالب الذكية', 'en' => 'Smart Templates'],
                'slug'          => 'smart-templates',
                'description'   => ['ar' => 'أنشئ العقود والمذكرات من قوالب جاهزة تتعبّأ تلقائياً ببيانات القضية بضغطة واحدة.', 'en' => 'Generate contracts and memos from templates auto-filled with case data in one click.'],
                'icon'          => 'heroicon-o-document-duplicate',
                'price_monthly' => 39,
                'price_yearly'  => 390,
                'currency'      => 'EGP',
                'category'      => 'productivity',
                'sort_order'    => 7,
            ],
            [
                'name'          => ['ar' => 'تتبّع الوقت وفوترة الساعات', 'en' => 'Time Tracking & Billing'],
                'slug'          => 'time-billing',
                'description'   => ['ar' => 'سجّل ساعات العمل على كل قضية وحوّلها إلى فاتورة احترافية تلقائياً.', 'en' => 'Log billable hours per case and convert them into a professional invoice automatically.'],
                'icon'          => 'heroicon-o-clock',
                'price_monthly' => 59,
                'price_yearly'  => 590,
                'currency'      => 'EGP',
                'category'      => 'finance',
                'sort_order'    => 8,
            ],
            [
                'name'          => ['ar' => 'تقسيط الأتعاب', 'en' => 'Fee Installments'],
                'slug'          => 'fee-installments',
                'description'   => ['ar' => 'قسّم أتعاب القضية على دفعات مجدولة يدفعها العميل أونلاين مع تذكيرات تلقائية.', 'en' => 'Split case fees into scheduled installments the client pays online, with automatic reminders.'],
                'icon'          => 'heroicon-o-banknotes',
                'price_monthly' => 49,
                'price_yearly'  => 490,
                'currency'      => 'EGP',
                'category'      => 'finance',
                'sort_order'    => 9,
            ],
            [
                'name'          => ['ar' => 'توقّع نتيجة القضية AI', 'en' => 'AI Case Outcome Prediction'],
                'slug'          => 'ai-case-predict',
                'description'   => ['ar' => 'تقدير احتمالية كسب القضية بالذكاء الاصطناعي بناءً على وقائعها والسوابق المشابهة.', 'en' => 'AI estimates the likelihood of winning a case based on its facts and similar precedents.'],
                'icon'          => 'heroicon-o-presentation-chart-line',
                'price_monthly' => 129,
                'price_yearly'  => 1290,
                'currency'      => 'EGP',
                'category'      => 'ai',
                'sort_order'    => 10,
            ],
            [
                'name'          => ['ar' => 'حاسبة المواعيد القانونية', 'en' => 'Legal Deadline Calculator'],
                'slug'          => 'legal-deadlines',
                'description'   => ['ar' => 'احسب آجال الطعن والاستئناف والنقض تلقائياً من تاريخ الحكم، مع تنبيهات قبل انتهاء كل أجل.', 'en' => 'Auto-compute appeal/cassation/objection deadlines from the verdict date, with alerts before each lapses.'],
                'icon'          => 'heroicon-o-calendar-days',
                'price_monthly' => 69,
                'price_yearly'  => 690,
                'currency'      => 'EGP',
                'category'      => 'legal',
                'sort_order'    => 11,
            ],
            [
                'name'          => ['ar' => 'تطبيق المحامي (PWA)', 'en' => 'Lawyer App (PWA)'],
                'slug'          => 'lawyer-pwa',
                'description'   => ['ar' => 'حوّل واجهة المحامي إلى تطبيق قابل للتثبيت على الهاتف للوصول السريع لقضاياك وجلساتك.', 'en' => 'Turn the lawyer interface into an installable phone app for quick access to cases and hearings.'],
                'icon'          => 'heroicon-o-device-phone-mobile',
                'price_monthly' => 39,
                'price_yearly'  => 390,
                'currency'      => 'EGP',
                'category'      => 'productivity',
                'sort_order'    => 12,
            ],
            [
                'name'          => ['ar' => 'مزامنة التقويم', 'en' => 'Calendar Sync'],
                'slug'          => 'calendar-sync',
                'description'   => ['ar' => 'اشترك في تقويم جلساتك من Google Calendar أو Apple عبر رابط ICS آمن يتحدّث تلقائياً.', 'en' => 'Subscribe to your hearings calendar from Google or Apple via a secure auto-updating ICS link.'],
                'icon'          => 'heroicon-o-calendar',
                'price_monthly' => 29,
                'price_yearly'  => 290,
                'currency'      => 'EGP',
                'category'      => 'productivity',
                'sort_order'    => 13,
            ],
            [
                'name'          => ['ar' => 'النسخ الاحتياطي السحابي', 'en' => 'Cloud Backup'],
                'slug'          => 'cloud-backup',
                'description'   => ['ar' => 'صدّر نسخة كاملة من بيانات مكتبك في أي وقت، مع خيار الرفع السحابي التلقائي.', 'en' => 'Export a full copy of your office data anytime, with optional automatic cloud upload.'],
                'icon'          => 'heroicon-o-cloud-arrow-up',
                'price_monthly' => 49,
                'price_yearly'  => 490,
                'currency'      => 'EGP',
                'category'      => 'general',
                'sort_order'    => 14,
            ],
            [
                'name'          => ['ar' => 'الفاتورة الإلكترونية والضرائب', 'en' => 'E-Invoice & Tax'],
                'slug'          => 'einvoice-tax',
                'description'   => ['ar' => 'أنشئ فواتير إلكترونية بنظام QR متوافق مع متطلبات الفوترة، مع تقارير ضريبية.', 'en' => 'Generate e-invoices with a compliant QR code and tax reports.'],
                'icon'          => 'heroicon-o-qr-code',
                'price_monthly' => 79,
                'price_yearly'  => 790,
                'currency'      => 'EGP',
                'category'      => 'finance',
                'sort_order'    => 15,
            ],
            [
                'name'          => ['ar' => 'التكامل مع المحاكم', 'en' => 'Court Integration'],
                'slug'          => 'court-sync',
                'description'   => ['ar' => 'استيراد حالات القضايا ومواعيد الجلسات من بوابات المحاكم الإلكترونية (حيثما توفّر).', 'en' => 'Import case statuses and hearing dates from court portals (where available).'],
                'icon'          => 'heroicon-o-building-library',
                'price_monthly' => 99,
                'price_yearly'  => 990,
                'currency'      => 'EGP',
                'category'      => 'legal',
                'sort_order'    => 16,
            ],
        ];

        foreach ($addons as $addonData) {
            Addon::updateOrCreate(['slug' => $addonData['slug']], $addonData);
        }
    }
}
